# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3bbb13be4e855f1d88b95c505dfe0b0d5527c77fa8c5992e715dba6fd9e07a0a1139c4cbb786a6dbe36ab082cb1d6b7fb84cff7e40f56c542bbac77ac303a6c

test:
  secret_key_base: a3dfc20e511b6a5cf8e83c1ba98af11a808e7278813c70c08d5d9a5643ca670bca52ffdc61b5a15cf93b0cc7ba8ba63ff050ab5e0691468935ad45342d448440

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
